language: java

jdk:
  - openjdk11

env:
  global:
    - SONARTYPE_USERNAME=awPAYN4P
    - secure: "qCkUXVfoVaRhhuA7QO7zH699FqZRrs6CWH27aHcXRgXjR+u6mCQlYXj0ehI/uh2XmGAWg4K7rzHLw/fc4murEL21snQPb+Ut/Xjr85HCvPeNfnU9Hg51qBYhPoWu9Yr6LR+SvP0B3c0Usne1PEECgNWfWm5EctHFJH6yC51DLB6ejwTxX5UNTOkcTDrhL9JITuqKX3HUcA+UIeWA7S7ixNIV8chiFSm4dyIe7TA0RDnYLUfRH8E1dK/yqzaaIjXplxpyGCJZ+/u9gs5nUd4lLtpeEJsTktCl7yWrzDb+fZ5pBuV3GozJBPJ0RMN1Dy/Zz7lSBo9wAu1kXMUjiCDfyvA0eWfAWw19lx6V+9bh3ZKN//YdIQJfiIRsMvqry5Lx38S5ApKbS86L2TovjEZ3xhjOFyNPUVRFSzg6h5B22Ss++AAVP/spS5vcflEqIMRZYpDs7T7K33D9YGhIjq7XsrxSWY1X8kOsRjpECjjVIXJ5lKWBO86f5qNTEYy1uboc62AFQJcR7wo9FBi2Hu9Hpe5DoXTgEMck6dMmTVhi908CS9QFX2AbtwahUuWZ6o9+u5ab+VJguqK+zg2J//11p7kdXPKI/+TalR4DcyUNObz8HMt9yEBrypbHQF4dofy/+jdqRe+5SdV0h/yeFbRQXNNNOcMOEcGHUB1HX/fPM0o="

install:
  - skip

script:
  - mvn --settings .mvn/settings.xml install

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && mvn --settings .mvn/settings.xml deploy"

cache:
  directories:
    - $HOME/.m2

branches:
  except:
    - gh-pages

notifications:
  email:
    - joerg.hohwiller@googlemail.com
